### ISSUE TITLE
Can I use `bigsur` for macOS 10.15 `Catalina`?

### ISSUE THREAD

**Issue by penguin806** [susll/HP-ProDesk-680-G6-Hackintosh#2]
Since macOS 11 bigsur it added ARM support, which is useless on hackintosh, so I'd like to choose Catalina for maximum stability.

**Comment by susll** [comment]
I'm not sure. Although I started with bigsure, this config has been updated quite a bit. Maybe need to try.

**Comment by penguin806** [comment]
I got it, thank you!
