### ISSUE TITLE
Can I updata to ventura from monterey by using this monterey efi?

### ISSUE THREAD

**Issue by Leslie-DD** [susll/HP-ProDesk-680-G6-Hackintosh#3]
Ventura now is available on October 24.

**Comment by Leslie-DD** [comment]
看大佬最近又更新了monterey的efi，不想重装ventura，想通过monterey升级，仓库里的monterey或者ventura efi升级好使吗？

**Comment by susll** [comment]
可以直接用monterey的efi，验证过可以直升      ventura是beta版本我试验的，很久没更新了 ，已经删掉了

**Comment by Leslie-DD** [comment]
赞，昨晚给我自升级了，已经升上来了
