### ISSUE TITLE
HP Prodesk 680 G6 i5-10500 安装进度条还剩18分钟时自动重启，重启后又进入Mac Recovery界面

### ISSUE THREAD

**Issue by penguin806** [susll/HP-ProDesk-680-G6-Hackintosh#4]
大佬，请问该怎样定位故障所在呢，突然重启，看不到日志。试过Monterey、Ventura，一样的症状。

**Comment by penguin806** [comment]
已解决，是SATA固态的问题，更换后正常安装

**Comment by Promise-hub** [comment]
请问你有修改过owner的EFI吗（比如三码什么的），我之前也是卡在进度条然后重启，重新进入，以为是别的问题，现在不确定是不是因为我修改了owner的三码的问题，导致现在直接卡在了跑代码的页面，

**Comment by Promise-hub** [comment]
> 已解决，是SATA固态的问题，更换后正常安装

请问你有修改过owner的EFI吗（比如三码什么的），我之前也是卡在进度条然后重启，重新进入，以为是别的问题，现在不确定是不是因为我修改了owner的三码的问题，导致现在直接卡在了跑代码的页面，
